output: 
    logger:
        #- type: MultiPlotLogger
        #  quantities: [z, E, p, T, qv, qc]
        #  file_name: time_series
        #  file_path: ./output/time_stamp/
        #  file_extension: png
        - type: NetCDFLogger
        #file_name: time_series
        #file_name: no_rad_no_turb
          file_name: dummy
        #file_path: ./output/time_stamp/
globals:
    #file_path: ./output/time_stamp/
    file_path: ./output/dummy/
    executer: numpy
initial_conditions:
    groups: 500
    #groups: 50000
    dt: 0.2
    output_step: 1
    t_max: 1400
    T: 281.7
    p: 89880.
    qv: 0.0077
    l: 50.
    w: 1.
    z0: 1000.
    particle_distribution:
        type: double_log_normal
        ratio: 0.6
        mu1: 2.e-8
        sigma1: 1.4 
        mu2: 7.5e-8
        sigma2: 1.6
        total: 100.e+6
        #type: marine_ccn
        #file_name: ./input/marine_aerosol_data_from_review_noGCCN.dat
        #total: 100e6
    radiation_schema:
        #type: libradtran
        #dz: 5
        #mode: thermal
        type: stefan_boltzmann
        factor: 1.0
        #type: no_radiation
    turbulence_schema:
        #type: gauss_turbulence
        #std: 0.0001
        #type: markov_schema
        #epsilon: 50.e-4
        type: no_turbulence
    atmosphere_schema:
        #type: afglus
        #atmosphere_file: ./input/afglus.dat
        type: linear_and_hydrostatic
